### ISSUE TITLE
Ability to check argument passed to cron job already processing to avoid duplicated cron job

### ISSUE THREAD

**Issue by ronald2wing** [WPBP/CronPlus#9]
Is there any way to do that? Can we add this feature?

**Comment by Mte90** [comment]
Are you talking about check if the cronjob was executed or it is running?

**Comment by ronald2wing** [comment]
I mean something similar to this https://github.com/veeqo/activejob-uniqueness
But yea, checking a cronjob with specific arguments was executed will also work.
Thank you!

**Comment by Mte90** [comment]
WordPress doesn't have something like that.

We can know when it was the last time it was executed, there is a transient in the database that save that time.
Also we can know if the request is a wp-cron.php one https://developer.wordpress.org/reference/functions/wp_doing_cron/ but for this need is not useful.

So the only solution could be check if based the time configured if the cronjob was executed in that time.

**Comment by ronald2wing** [comment]
Is setting a post attribute to know if it is processing or not a possible solution?

**Comment by Mte90** [comment]
Well creating an option that after that is deleted is not very good for performance.

For those cases more advanced I suggests to use https://github.com/woocommerce/action-scheduler

**Comment by ronald2wing** [comment]
Thank you, I will use the unique feature here: https://github.com/woocommerce/action-scheduler/issues/1031#issuecomment-1961637862

**Comment by ronald2wing** [comment]
@Mte90 Can we reopen this as a feature request? Since this is quite a popular feature for action-schedulers.

**Comment by Mte90** [comment]
The purpose of this library is more simpler and it isn't an action scheduler advanced.
I suggest for more advanced stuff that library that is used in context where can confirm that works.
